version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
  ignore:
  - dependency-name: firebase-admin
    versions:
    - 9.4.2
    - 9.5.0
    - 9.6.0
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
  - dependency-name: actions-on-google
    versions:
    - 2.13.0
  - dependency-name: lodash
    versions:
    - 4.17.20
